# Generated by Django 4.1.1 on 2022-10-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('is_car_park', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DoorRecord',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('recorded_date', models.CharField(max_length=30)),
                ('recorded_time', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('doors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.doors')),
            ],
        ),
    ]
