# Generated by Django 4.1.1 on 2022-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorrecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doors',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
