# Generated by Django 4.1.1 on 2022-10-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doorrecord',
            old_name='door_actions',
            new_name='door_action',
        ),
    ]
