# Generated by Django 4.1.1 on 2022-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_doorrecord_id_alter_doors_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='is_car_park',
            field=models.BooleanField(default=False),
        ),
    ]
